import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import {Heebo,Inter} from "next/font/google";
const heebo = Heebo({subsets:["latin"],weight: ["400","700","900","500","600"]})
const inter = Inter({subsets:["latin"],weight: ["400","700","500","600"]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={heebo.className}>
        <Header font={inter}/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
